### ISSUE TITLE
Two Issues

### ISSUE THREAD

**Issue by andyrrm** [Deeplocal/scrubber#1]
For starters - I really like this idea. But the execution here leaves a lot to be desired. I'm running into two issues that are preventing me from proceeding:

**Issue 1**

Upon the initial execution of `node index`, everything works fine; I am able to insert my client ID and client secret. When I go to http://<My Raspberry Pi’s ip>:5000, I get the page with the login button, but upon clicking, I get redirected to a blank page that says `INVALID_CLIENT: Invalid redirect URI`. I have double, triple, quadruple checked that my Redirect URI is correct.
That brings me to:

**Issue 2**

Since I can't put in a valid code, I have to reset the scrubber app. Upon attempting `node index` again, I get:

```
Scrubber is Scrubbing!
/home/pi/Projects/scrubber/index.js:212
            spotifyApi.setAccessToken(config.tokens.access_token);
                                                    ^

TypeError: Cannot read property 'access_token' of undefined
    at fs.readFile (/home/pi/Projects/scrubber/index.js:212:53)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:532:3)

```

This stays like this until I delete the entire scrubber folder and re-clone it. Help is very much appreciated because I've come so far.

**Comment by AdnanDL** [comment]
Sorry to hear you're having trouble here

**Issue 1**
Could you reconfirm that your redirect URI is "http://<Your Raspberry Pi’s ip>:5000"  and not just "<Your Raspberry Pi’s ip>". 

**Issue 2**
I think that's due to the error in the first step. You should be able to try again (without re-cloning) if you delete the config.json file

**Comment by andyrrm** [comment]
Ha, yes, I'm using the actual IP of my Raspberry Pi.

Deleting the config file fixed issue 2. I'm still unable to get past the other issue however. Now it's redirecting me to `Illegal redirect_uri`

**Comment by AdnanDL** [comment]
Are you adding the **:5000** to your redirect URI on the Spotify Dashboard ?

**Comment by dizzy1832** [comment]
Hello, I'm running in the same problem with the "Illegal redirct_uri." 
I'm adding the "http://192.xxx.x.xxx:5000" and still get the same error after I click login.

**Comment by taylortabb** [comment]
Just to confirm
1. are you on a network where devices can see and communicate with each other on LAN? (i.e. a large managed Wi-Fi network like at a university might create issues) 

2. Under the Scrubber app in your Spotify dashboard, do your Redirect URIs have the same form as below? ![image of dashboard](https://i.imgur.com/o1a0Cru.png)

**Comment by dizzy1832** [comment]
yes

**Comment by andyrrm** [comment]
![image](https://user-images.githubusercontent.com/53543020/79009797-3744b200-7b15-11ea-8f49-6832fe76bde1.png)
yes

**Comment by AdnanDL** [comment]
@andyrmiller Your screenshot above has **500** instead of **5000** and you have it as **https** instead of **http**

**Comment by dizzy1832** [comment]
I add and save. I get a green banner saying that my "data for my application has been saved."

**Comment by andyrrm** [comment]
![image](https://user-images.githubusercontent.com/53543020/79009955-a6220b00-7b15-11ea-806b-f585f5180b7f.png)
my bad, with 5000 I still get illegal redirct_uri.

**Comment by dizzy1832** [comment]
Thank you, I will try it.

**Comment by andyrrm** [comment]
![image](https://user-images.githubusercontent.com/53543020/79010979-e4202e80-7b17-11ea-91af-33b9b4e1bb3d.png)
Here is the error I get when I got to the URI address

**Comment by AdnanDL** [comment]
This only works with **http** and not **https**, so please make sure your Spotify dashboard setting has http:// and not https:// like you have it above

**Comment by andyrrm** [comment]
I corrected to http. Still getting Illegal redirect_uri message. This is what the terminal displays for me:
![image](https://user-images.githubusercontent.com/53543020/79011368-bf788680-7b18-11ea-88d9-d572cadaf9fb.png)

**Comment by AdnanDL** [comment]
Ah the reason looks like you have an ipv6 address instead of an ipv4. 
We look up what the ip of your device is with 

``cmd.get(
    "hostname -I",
    function (err, data){
        ipAddr = `http://${data.trim()}:5000`;
    }
);``

If you change that line ipAddr line with your ip  it should then point to that address

`ipAddr = 'http://192.168.7.247:5000';`

In your terminal you would see "Please enter your code from http:192.168.7.247:5000"

**Comment by andyrrm** [comment]
Forgive me for my lack of coding abilities - what's the best way to replace the ipAddr line?

**Comment by dizzy1832** [comment]
I get the same message as andyrmiller. I'm new to coding and my respects to all and thank you for helping the newbies.

**Comment by andyrrm** [comment]
> I get the same message as andyrmiller. I'm new to coding and my respects to all and thank you for helping the newbies.

I was able to edit the code in /scrubber by entering `nano index.js`. I scrolled down and changed the ipAddr line like stated above. Code works now.

**Comment by andyrrm** [comment]
@AdnanDL @taylortabb upon changing the ipAddr, I am able to get the code from the IP address link. However, I now get the following code:

```
Token info saved!
Downloading Songs!
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find ffmpeg
    at /home/pi/Projects/scrubber/node_modules/fluent-ffmpeg/lib/processor.js:136:22
    at /home/pi/Projects/scrubber/node_modules/fluent-ffmpeg/lib/capabilities.js:123:9
    at wrapper (/home/pi/Projects/scrubber/node_modules/async/dist/async.js:268:20)
    at next (/home/pi/Projects/scrubber/node_modules/async/dist/async.js:4582:24)
    at /home/pi/Projects/scrubber/node_modules/async/dist/async.js:321:20
    at /home/pi/Projects/scrubber/node_modules/fluent-ffmpeg/lib/capabilities.js:116:11
    at /home/pi/Projects/scrubber/node_modules/fluent-ffmpeg/lib/utils.js:223:16
    at F (/home/pi/Projects/scrubber/node_modules/which/which.js:68:16)
    at E (/home/pi/Projects/scrubber/node_modules/which/which.js:80:29)
    at /home/pi/Projects/scrubber/node_modules/which/which.js:89:16
Emitted 'error' event at:
    at emitEnd (/home/pi/Projects/scrubber/node_modules/fluent-ffmpeg/lib/processor.js:424:16)
    at /home/pi/Projects/scrubber/node_modules/fluent-ffmpeg/lib/processor.js:433:16
    at wrapper (/home/pi/Projects/scrubber/node_modules/async/dist/async.js:268:20)
    [... lines matching original stack trace ...]
    at wrapper (/home/pi/Projects/scrubber/node_modules/async/dist/async.js:268:20)
    at next (/home/pi/Projects/scrubber/node_modules/async/dist/async.js:4582:24)
    at /home/pi/Projects/scrubber/node_modules/async/dist/async.js:321:20
    at /home/pi/Projects/scrubber/node_modules/fluent-ffmpeg/lib/capabilities.js:519:16
    at /home/pi/Projects/scrubber/node_modules/fluent-ffmpeg/lib/processor.js:136:16

```

**Comment by taylortabb** [comment]
@andyrmiller could you type and enter the command `which ffmpeg` and let me know what the output is?

**Comment by andyrrm** [comment]
![image](https://user-images.githubusercontent.com/53543020/79030372-88709800-7b4d-11ea-9a99-47a1b8a29809.png)

getting no love lol

**Comment by taylortabb** [comment]
Actually that's good! No output means ffmpeg is not install or can't be found. Though I'm not sure why that would be the case, we can fix it— try typing and entering `npm i ffmpeg` and `npm i fluent-ffmpeg` then running the script again.

**Comment by andyrrm** [comment]
Getting a little bit further... I reset the config.json and reentered the id / secret / code:


```
Token info saved!
fs.js:909
  return binding.mkdir(pathModule.toNamespacedPath(path),
                 ^

Error: EEXIST: file already exists, mkdir 'songs'
    at Object.fs.mkdirSync (fs.js:909:18)
    at /home/pi/Projects/scrubber/index.js:76:24
    at FSReqWrap.oncomplete (fs.js:153:20)

```

**Comment by taylortabb** [comment]
awesome— this just means the folder "songs" already exists from the previous try at setting it up. Go ahead and delete it by navigating to the scrubber directory and typing `sudo rm -r songs` then try once more.

**Comment by andyrrm** [comment]
Oh lord... at this point I'm wondering if I should just wipe everything and start over.

```
Token info saved!
Downloading Songs!
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find ffmpeg
    at /home/pi/Projects/scrubber/node_modules/fluent-ffmpeg/lib/processor.js:136:22
    at /home/pi/Projects/scrubber/node_modules/fluent-ffmpeg/lib/capabilities.js:123:9
    at wrapper (/home/pi/Projects/scrubber/node_modules/async/dist/async.js:268:20)
    at next (/home/pi/Projects/scrubber/node_modules/async/dist/async.js:4582:24)
    at /home/pi/Projects/scrubber/node_modules/async/dist/async.js:321:20
    at /home/pi/Projects/scrubber/node_modules/fluent-ffmpeg/lib/capabilities.js:116:11
    at /home/pi/Projects/scrubber/node_modules/fluent-ffmpeg/lib/utils.js:223:16
    at F (/home/pi/Projects/scrubber/node_modules/which/which.js:68:16)
    at E (/home/pi/Projects/scrubber/node_modules/which/which.js:80:29)
    at /home/pi/Projects/scrubber/node_modules/which/which.js:89:16
Emitted 'error' event at:
    at emitEnd (/home/pi/Projects/scrubber/node_modules/fluent-ffmpeg/lib/processor.js:424:16)
    at /home/pi/Projects/scrubber/node_modules/fluent-ffmpeg/lib/processor.js:433:16
    at wrapper (/home/pi/Projects/scrubber/node_modules/async/dist/async.js:268:20)
    [... lines matching original stack trace ...]
    at wrapper (/home/pi/Projects/scrubber/node_modules/async/dist/async.js:268:20)
    at next (/home/pi/Projects/scrubber/node_modules/async/dist/async.js:4582:24)
    at /home/pi/Projects/scrubber/node_modules/async/dist/async.js:321:20
    at /home/pi/Projects/scrubber/node_modules/fluent-ffmpeg/lib/capabilities.js:519:16
    at /home/pi/Projects/scrubber/node_modules/fluent-ffmpeg/lib/processor.js:136:16

```

**Comment by andyrrm** [comment]
`which ffmpeg` isn't returning anything so I'm installing it again.

**Comment by andyrrm** [comment]
I'm getting this when I try to install them:

```
pi@raspberrypi:~/Projects/scrubber $ npm i ffmpeg
npm WARN scrubber@1.0.0 No repository field.

+ ffmpeg@0.0.4
updated 1 package in 52.923s
pi@raspberrypi:~/Projects/scrubber $ npm i fluent-ffmpeg
npm WARN scrubber@1.0.0 No repository field.

+ fluent-ffmpeg@2.1.2
updated 1 package in 54.476s

```

and upon putting in `which ffmpeg` again, I get nothing.

**Comment by andyrrm** [comment]
Alright, fixed it. I ran `sudo apt-get install ffmpeg` and it finally installed. Rest of the code worked as normal. 

Of course the music sounds like a hellportal just opened, but that's another animal...
I can close this one and create a new issue if you'd like. But the speaker-test audio works just fine from the speakers, so it's not a connection issue.

**Comment by taylortabb** [comment]
glad this issue is resolved! yeah go ahead and open a new one for the speaker issue. @dizzy1832 feel free to open another issue if you're still having issues also.

**Comment by taylortabb** [comment]
glad this issue is resolved! yeah go ahead and open a new one for the speaker issue. @dizzy1832  feel free to open another issue if you're still having issues also.

**Comment by taylortabb** [comment]
To clarify for anyone looking at this having the ffmpeg issue, here's our soltion:

you'll want to enter 

```
sudo apt-get install ffmpeg
npm i ffmpeg
npm i fluent-ffmpeg
```

Then delete your songs repository with `sudo rm -r songs` then reboot the device `sudo reboot now` and run the script again! :)
