### ISSUE TITLE
20 seconds of audio sounds like a hell portal opening

### ISSUE THREAD

**Issue by andyrrm** [Deeplocal/scrubber#2]
Reference: #1 

Everything is 90% complete; finally got the code up and running, connected to spotify's api, all the soldering, and the speakers are connected.

Upon testing the speakers using `speaker-test`, they work just fine:
https://photos.app.goo.gl/eSfwUGsmSotzdrH36

But when running scrubber and touching the wires together, I get 20 seconds of obnoxious static-y  white-noise-esque sounds:
https://photos.app.goo.gl/zCFLZWHM44yVbAo9A

So it definitely isn't an issue with the speakers or the connection. kinda stumped here.

**Comment by taylortabb** [comment]
Let's go through these steps, and let me know the results (this should not yield a solution, just troubleshooting)

1. `speaker-test -c2 --test=wav -w /usr/share/sounds/alsa/Front_Center.wav`
_does it play audio?_

2.` sudo apt-get install -y mpg123` then `mpg123 http://ice1.somafm.com/u80s-128-mp3`
_does it play audio?_

3. `sudo reboot now`, and try running scrubber again. 
_does it play audio?_

**Comment by andyrrm** [comment]
1. Yes, audio works just fine.

2. Yes, audio works just fine and sounds great.

3. Rebooted, audio works now!

Not sure what the problem was, but... Hey, it works! Thanks!

**Comment by taylortabb** [comment]
Woo! Glad you got it working.
