### ISSUE TITLE
Error on first run of `node index`

### ISSUE THREAD

**Issue by naviztirf** [Deeplocal/scrubber#5]
I have installed on a pi w using buster lite. Readme.md is a little out of date, as node has since dropped support for the arm61. The latest supported version (which I installed via binaries) is 11.15.0.

Everything appears to install properly without errors until it gets to downloading songs from Spotify. Here is the error immediately after entering my credentials for the scrubber app:

Token info saved!
Downloading Songs!
(node:1516) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'preview_url' of undefined
    at download (/home/pi/Projects/scrubber/index.js:142:20)
    at /home/pi/Projects/scrubber/index.js:119:13
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:1516) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1516) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

After which the process appears to hang (does not exit).  I see the connection was successful in my spotify console. 

Any help is appreciated... I really like the concept of this project and want to see it working! :)

**Comment by naviztirf** [comment]
I should add that on second run I get:

Scrubber is Scrubbing!

When I touch my momentary switch I see:

Song folder Exists!
There are 0 available
Playing 0 now
1

So it appears the issue just effects the connection to Spotify, and otherwise everything is working.

**Comment by AdnanDL** [comment]
Hey could you refer to [this thread here](https://github.com/Deeplocal/scrubber/issues/4#issue-631862161) it looks like it might be an issue of not having a song history for Scrubber to use

**Comment by naviztirf** [comment]
You are correct, that's what seems to have happened here. I did have a spotify account with playlists created, but hadn't played anything recently enough for the "top 10" to be populated. 

To fix I played through my playlist a few times on Spotify, then deleted the "scrubber/songs" directory and restarted scrubber. The songs then downloaded and it works!  Thanks.
